name: scratch
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _py-xgboost-mutex=2.0=cpu_2
  - adwaita-icon-theme=48.0=h06a4308_0
  - ansi2html=1.9.1=py310h06a4308_0
  - anyio=4.6.2=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h5eee18b_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py310h06a4308_0
  - async-timeout=5.0.1=py310h06a4308_0
  - at-spi2-atk=2.34.2=hdb5d850_0
  - at-spi2-core=2.36.0=hdb5d850_1
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=24.3.0=py310h06a4308_0
  - babel=2.16.0=py310h06a4308_0
  - beautifulsoup4=4.12.3=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310h06a4308_0
  - blinker=1.9.0=py310h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.7.14=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py310h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dash=2.14.2=py310h06a4308_0
  - dash_cytoscape=0.3.0=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py310h06a4308_0
  - epoxy=1.5.4=h7f8727e_2
  - et_xmlfile=1.1.0=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - flask=3.0.3=py310h06a4308_0
  - flask-compress=1.13=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gettext=0.21.0=hedfda30_2
  - gevent=23.9.1=py310h5eee18b_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.78.1=py310h42194e9_2
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.1.1=py310h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk3=3.24.21=h0fee60c_7
  - gts=0.7.6=hb67d8dd_3
  - h11=0.14.0=py310h06a4308_0
  - harfbuzz=10.2.0=hf296adc_0
  - hicolor-icon-theme=0.17=h06a4308_2
  - httpcore=1.0.2=py310h06a4308_0
  - httpx=0.27.0=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - interpret=0.6.11=pyhd8ed1ab_0
  - interpret-core=0.6.11=pyhd8ed1ab_1
  - ipykernel=6.29.5=py310h06a4308_1
  - ipython=8.30.0=py310h06a4308_0
  - ipywidgets=8.1.5=py310h06a4308_0
  - itsdangerous=2.2.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.4=py310h06a4308_1
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py310h06a4308_0
  - jsonschema=4.23.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.2.0=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - jupyter_events=0.10.0=py310h06a4308_0
  - jupyter_server=2.14.1=py310h06a4308_0
  - jupyter_server_terminals=0.4.4=py310h06a4308_1
  - jupyterlab=4.3.4=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - jupyterlab_widgets=3.0.13=py310h06a4308_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libebm=0.6.11=h84d6215_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.56.3=hf6914bd_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.4.7=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxgboost=3.0.1=h6a678d5_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lightgbm=4.6.0=py310h6a678d5_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.44.0=py310hc1e8f15_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_1
  - matplotlib=3.10.0=py310h06a4308_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=2.0.4=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - multiprocess=0.70.15=py310h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py310h06a4308_0
  - nbconvert=7.16.4=hd3eb1b0_1
  - nbconvert-core=7.16.4=py310h06a4308_1
  - nbconvert-pandoc=7.16.4=hd3eb1b0_1
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - notebook=7.0.6=py310h06a4308_0
  - notebook-shim=0.2.3=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.61.2=py310h699fe88_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py310h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - overrides=7.4.0=py310h06a4308_0
  - packaging=24.2=py310h06a4308_0
  - pandas=2.2.3=py310h6a678d5_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h0fee60c_1
  - parallel=20250622=ha770c72_0
  - parso=0.8.4=py310h06a4308_0
  - pathos=0.3.0=py310h06a4308_0
  - patsy=1.0.1=py310h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.38.2=0_h5eee18b_perl5
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.0.0=py310hcea889d_1
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py310h06a4308_0
  - plotly=5.24.1=py310h2f386ee_1
  - ply=3.11=py310h06a4308_0
  - poppler=24.09.0=hcf11d46_1
  - poppler-data=0.4.11=h06a4308_1
  - pox=0.3.3=py310h06a4308_0
  - ppft=1.7.6.7=py310h06a4308_0
  - prometheus_client=0.21.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=3.0.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_1
  - pyqt5-sip=12.13.0=py310h5eee18b_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-json-logger=3.2.1=py310h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-forecasting=1.4.0=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - qtconsole=5.6.1=py310h06a4308_0
  - qtpy=2.4.1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py310h06a4308_0
  - requests=2.32.3=py310h06a4308_1
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - salib=1.5.1=pyhd8ed1ab_2
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.15.1=py310h5f9d8c6_0
  - seaborn=0.13.2=py310h06a4308_2
  - send2trash=1.8.2=py310h06a4308_1
  - setuptools=75.1.0=py310h06a4308_0
  - shap=0.47.2=py310h49ed93b_0
  - sip=6.7.12=py310h6a678d5_1
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=py310h8ad78c3_1
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py310h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py310h06a4308_0
  - terminado=0.17.1=py310h06a4308_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tigramite=5.2.7.0=pyhd8ed1ab_0
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.5.1=py310_cu124
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu124
  - tornado=6.4.2=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.2.3=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - widgetsnbextension=4.0.13=py310h06a4308_0
  - xgboost=3.0.1=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zope=1.0=py310h06a4308_1
  - zope.event=5.0=py310h06a4308_0
  - zope.interface=7.1.1=py310h5eee18b_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - agate==1.13.0
      - agate-dbf==0.2.3
      - agate-excel==0.4.1
      - agate-sql==0.7.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - aplr==10.9.0
      - cloudpickle==3.1.1
      - csvkit==2.1.0
      - dbfread==2.0.7
      - dcor==0.6
      - fsspec==2025.3.0
      - graphviz==0.20.3
      - grpcio==1.70.0
      - holidays==0.75
      - isodate==0.7.2
      - leather==0.4.0
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - lingam==1.11.0
      - mambapy==1.2.0
      - markdown==3.7
      - multidict==6.2.0
      - numdifftools==0.9.41
      - olefile==0.47
      - parsedatetime==2.6
      - pip==25.3
      - progressbar2==4.5.0
      - propcache==0.3.0
      - protobuf==5.29.3
      - psy==0.0.1
      - pygam==0.10.1
      - python-slugify==8.0.4
      - python-utils==3.9.1
      - pytimeparse==1.1.8
      - pytorch-lightning==2.5.2
      - semopy==2.3.11
      - sqlalchemy==2.0.44
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchmetrics==1.7.4
      - werkzeug==3.1.3
      - xlrd==2.0.2
      - yarl==1.18.3
prefix: /usr/local/data/elisejzh/miniconda3/envs/scratch
